export const sideMenuLinks = [
  {
    route:'/',
    label:'ホーム',
    sectionId:'home'
  },
  {
    route:'#about',
    label:'自己紹介',
    sectionId:'about'
  },
  {
    route:'#skils',
    label:'使用言語',
    sectionId:'skils'
  },
  {
    route:'#projects',
    label:'開発実績',
    sectionId:'projects'
  },
  {
    route:'#contact',
    label:'コンタクト',
    sectionId:'contact'
  },
]